namespace SourceGenerator;

internal static class Constants
{
    internal const string AutoGenerated = "// AUTO-GENERATED by SourceGenerator\r" +
        "\n// this file will be automatically regenerated each time the ISignal interface is modified";
}
